In [1]:
import plotly.express as px
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df1 = pd.read_csv('output.csv')
df2 = pd.read_csv('output2.csv')
df = pd.concat([df1,df2])

In [3]:
df.head()

,room_id,name,title,price,rating_value,rating_reviewCount,bed_info,image_urls,latitude,longitude
0,45331539,Studio alto padrão no Umarizal,Apartamento ⋅ Belém,2754.91,5.00,4,1 quarto; 2 camas,https://a0.muscache.com/im/pictures/hosting/Ho...,-1.439341,-48.491214
1,1531110121855584800,Cobertura Privativa no Umarizal,Apartamento ⋅ Belém,667.76,0.00,0,1 quarto; 1 cama de casal,https://a0.muscache.com/im/pictures/hosting/Ho...,-1.446160,-48.485780
2,605826375496430600,Apto um quarto com piscina perto do Bosque,Condomínio ⋅ Marco,1721.93,4.87,62,1 quarto; 2 camas,https://a0.muscache.com/im/pictures/057646b2-6...,-1.432160,-48.462530
3,1395198115350306300,Bayview Deluxe Umarizal,Apartamento ⋅ Belém,3984.98,5.00,20,1 quarto; 1 cama,https://a0.muscache.com/im/pictures/hosting/Ho...,-1.440100,-48.491500
4,1512523931462295000,Excelente suíte em apto com preço US$ 120/dia,Lugar para ficar em Belém,758.36,0.00,0,1 quarto; 1 cama,https://a0.muscache.com/im/pictures/hosting/Ho...,-1.429769,-48.488477

In [4]:
df[['room_info', 'bed_info_detail']] = df['bed_info'].str.split(';', expand=True)

df['room_info'] = df['room_info'].str.strip()
df['bed_info_detail'] = df['bed_info_detail'].str.strip()

df['full_price'] = df['price']*11

In [5]:
print(f'Before dropping duplicates: {len(df)}')
df = df.drop_duplicates()
df = df.loc[~df['room_id'].duplicated()]
print(f'Before after duplicates: {len(df)}')

Before dropping duplicates: 560
Before after duplicates: 412

In [6]:
df = df[['name','title','price','full_price','rating_value','rating_reviewCount','latitude','longitude','room_info','bed_info_detail']]

In [7]:
df = df.rename({
    'title':'category',
    'bed_info_detail':'bed_info'
},axis=1)

In [8]:
import plotly.express as px

fig = px.scatter_map(
    df,
    lat="latitude",
    lon="longitude",
    hover_name="name",
    hover_data=["price", "bed_info"],
    color="price",
    zoom=10,
    height=2600,
    width=2000
)

# Use an open Mapbox style (no token needed)
fig.update_layout(mapbox_style="open-street-map")

# Automatically fit all points
fig.update_layout(
    mapbox=dict(
        bounds=dict(
            west=df['longitude'].min(),
            east=df['longitude'].max(),
            south=df['latitude'].min(),
            north=df['latitude'].max(),
        )
    )
)

# Optional: adjust margins for clean PNG export
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})

# Export to PNG
fig.write_image("scatter_map.png", scale=10)

In [11]:
fig = px.scatter_map(
        df,
        lat='latitude',
        lon='longitude',
        color='price',        # Color markers by city
        hover_name='name',   # Display city name on hover
        zoom=10,
        title='Distribuição apartamentos COP30', width=1980, height=1080
    )

fig.show()

In [13]:
apartamento_df = df.loc[df['category'].str.contains('Apartamento')==True]
casa_df = df.loc[df['category'].str.contains('Casa')==True]
other_df = df.loc[
    (~df['category'].str.contains('Apartamento')) &
    (~df['category'].str.contains('Casa'))
]

In [14]:
apartamento_df.describe()

,price,full_price,rating_value,rating_reviewCount,latitude,longitude
count,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000
mean,4360.793290,47968.726189,0.971205,5.824104,-1.438754,-48.476161
std,2170.913009,23880.043102,1.954685,23.751058,0.019121,0.012702
min,461.700000,5078.700000,0.000000,0.000000,-1.475790,-48.500400
25%,2746.865000,30215.515000,0.000000,0.000000,-1.449832,-48.487250
50%,4006.590000,44072.490000,0.000000,0.000000,-1.440547,-48.477900
75%,5705.890000,62764.790000,0.000000,0.000000,-1.432000,-48.466400
max,10239.060000,112629.660000,5.000000,278.000000,-1.374400,-48.447060

In [15]:
casa_df.describe()

,price,full_price,rating_value,rating_reviewCount,latitude,longitude
count,57.000000,57.000000,57.000000,57.000000,57.000000,57.000000
mean,3155.705439,34712.759825,0.255263,0.298246,-1.437123,-48.468874
std,2454.345861,26997.804469,1.093073,1.362310,0.031359,0.015521
min,255.570000,2811.270000,0.000000,0.000000,-1.505800,-48.502122
25%,1334.770000,14682.470000,0.000000,0.000000,-1.464700,-48.479000
50%,2362.240000,25984.640000,0.000000,0.000000,-1.431304,-48.468104
75%,3895.300000,42848.300000,0.000000,0.000000,-1.414640,-48.456600
max,8903.530000,97938.830000,5.000000,8.000000,-1.379753,-48.446300

In [16]:
other_df.describe()

,price,full_price,rating_value,rating_reviewCount,latitude,longitude
count,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000
mean,2110.159792,23211.757708,2.239167,22.666667,-1.444295,-48.475708
std,2097.146840,23068.615238,2.461395,36.256963,0.026531,0.015614
min,305.680000,3362.480000,0.000000,0.000000,-1.500262,-48.500080
25%,810.792500,8918.717500,0.000000,0.000000,-1.462783,-48.489225
50%,1296.990000,14266.890000,0.000000,0.000000,-1.449295,-48.479650
75%,2606.670000,28673.370000,4.902500,27.000000,-1.428772,-48.463783
max,10118.120000,111299.320000,5.000000,126.000000,-1.395410,-48.447831

In [10]:
df.to_csv('dados_final.csv',index=False)